version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/insurance
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbit
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  rabbit:
    restart: always
    image: rabbitmq:3-management
    ports:
      - 15672:15672
  celery:
    restart: always
    build: .
    command: celery -A InsuranceExchange worker --loglevel=info --concurrency=5
    volumes:
      - .:/insurance
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbit
      - web

volumes:
  postgres_data:
